resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
      
trigger:
  - none

parameters:
- name: environment
  type: object
  default:
   - Dev
   - Demo

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: tfVersion
  value: 1.1.0
- name: tfStateServiceConnection
  value: DTS-SHAREDSERVICES-PROD-Video Hearings
- name: project
  value: application
- group: external
  
stages:

################################################
# Check State. #################################

- stage: 'Check_Terraform_State'
  displayName: Check Terraform State
  jobs:
  - job: 'Check_Terraform_State'
    displayName: Check Terraform State
    steps:
    - template: pipeline-steps/check-state.yaml
      parameters:
        serviceConnection: ${{ variables.tfStateServiceConnection }}
        resourceGroup: vh-infra-core-tf
        storageAccountName: vhinfracoretf
        containerName: tfstate
        location: 'uk south'

################################################
# Terraform Plan. ##############################
- ${{ each env in parameters.environment }}:
  - stage: 'Terraform_Plan_${{ env }}'
    displayName: 'Terraform Plan ${{ env }}'
    jobs: 
    - job: 'Terraform_Plan_${{ env }}'
      displayName: 'Terraform Plan ${{ env }}'
      variables:
      - name: environment
        value: ${{ env }}
      - template: pipeline-steps/ado-vars.yaml
        # If another project comes along and wants to use the same pipeline file then make this a variable in the UI
        # but it might be better to template the pipeline more and have a different pipeline file
        # so that someone doesn't pick the wrong var in the dropdown
        # same comment as above ^^
      - name: environmentServiceConnection
        value: DTS-SHAREDSERVICES-${{ env }}-Video Hearings
      steps:
      - template: pipeline-steps/vh-tenant-replacement.yaml
        parameters:
          environment: ${{ variables.environment }}

      - template: pipeline-steps/ado-vars-to-tf.yaml
        parameters: 
          environment: ${{ variables.environment }}

      - template: pipeline-steps/plan-service-elevated.yaml
        parameters:
          environment: ${{ variables.environment }}
          location: 'UK South'
          stack: '09-video-hearing-core'
          project: $(project)
          product: 'vh'
          builtFrom: $(Build.Repository.Name)
          tfversion: $(tfversion)
          serviceConnection: ${{ variables.environmentServiceConnection }}
          backendServiceConnection: ${{ variables.tfStateServiceConnection }}
          activity_name: Video_Hearing_Core
          state_sub: $(vh_tf_state_sub)
          additional_tf_var: $(ado_vars_to_tf.ado_vars)

  ################################################
  # Terraform Apply Dev. #########################

  - stage: 'Terraform_Apply_${{ env }}'
    displayName: 'Terraform Apply ${{ env }}'
    variables:
      - group: vh-tenant-creds
      - name: environment
        value: ${{ env }}
      - group: external
      - template: pipeline-steps/ado-vars.yaml
        # If another project comes along and wants to use the same pipeline file then make this a variable in the UI
        # but it might be better to template the pipeline more and have a different pipeline file
        # so that someone doesn't pick the wrong var in the dropdown
      - name: project
        value: application
      # same comment as above ^^
      - name: environmentServiceConnection
        value: DTS-SHAREDSERVICES-${{ env }}-Video Hearings #OPS-APPROVAL-GATE-${{ parameters.env }}-ENVS
    jobs:
      - deployment: 'Terraform_Apply_${{ env }}'
        displayName: Terraform Apply ${{ env }}
        continueOnError: false
        environment: ${{ env }}
        strategy:
          runOnce:
            deploy:
              steps:
              - template: pipeline-steps/apply-service-elevated.yaml
                parameters:
                  environment: ${{ variables.environment }}
                  location: 'UK South'
                  stack: '09-video-hearing-core'
                  project: $(project)
                  product: 'vh'
                  builtFrom: $(Build.Repository.Name)
                  tfversion: $(tfversion)
                  serviceConnection: ${{ variables.environmentServiceConnection }}
                  backendServiceConnection: ${{ variables.tfStateServiceConnection }}
                  activity_name: Video_Hearing_Core
                  state_sub: $(vh_tf_state_sub)
                  additional_tf_var: $(ado_vars_to_tf.ado_vars)
