resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
      
trigger:
  - none

parameters:
- name: environment
  type: object
  default:
   - Dev
   - Demo
   - Prod
   - ITHC
   - STG
   - Test

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: tfVersion
  value: 1.1.0
- name: tfStateServiceConnection
  value: DTS-SHAREDSERVICES-PROD-Video Hearings
- group: external
  
stages:

################################################
# Check State. #################################

- stage: 'Check_Terraform_State'
  displayName: Check Terraform State
  jobs:
  - job: 'Check_Terraform_State'
    displayName: Check Terraform State
    steps:

    - ${{ each env in parameters.environment }}:
      - task: AzureCLI@2
        inputs:
          addSpnToEnvironment: true
          azureSubscription: DTS-SHAREDSERVICES-${{ env }}-Video Hearings
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: | 
            cd $(System.DefaultWorkingDirectory)
            echo "$servicePrincipalKey" > "$(System.DefaultWorkingDirectory)/key.txt"
            sed -i 's/~/+/g' key.txt
            echo "${{ env }}"
            cat $(System.DefaultWorkingDirectory)/key.txt

    - template: pipeline-steps/check-state.yaml
      parameters:
        serviceConnection: ${{ variables.tfStateServiceConnection }}
        resourceGroup: vh-infra-core-tf
        storageAccountName: vhinfracoretf
        containerName: tfstate
        location: 'uk south'

################################################
# Terraform Plan & Apply. ######################

- ${{ each env in parameters.environment }}:
  - template: pipeline-steps/terraform-plan-apply.yaml
    parameters:
      terraformVersion: ${{ variables.tfVersion }}
      env: ${{ env }}
      location: 'UK South'
      project: application
      environmentServiceConnection: DTS-SHAREDSERVICES-${{ env }}-Video Hearings
      tfStateServiceConnection: ${{ variables.tfStateServiceConnection }}
      stack: 09-video-hearing-core
      product: vh
      activityName: Video_Hearing_Core